//! SPEC §17.3 — `DryRunExecutor` isolation invariants. The executor MUST
//! construct an isolated runtime per call; caller state cannot be mutated.

use chrono::Utc;
use praxec_core::model::{ExecuteRequest, WorkflowInstance};
use praxec_core::ports::Executor;
use praxec_executors::DryRunExecutor;
use serde_json::{json, Value};

fn instance_stub() -> WorkflowInstance {
    WorkflowInstance {
        id: "wf_stub".into(),
        definition_id: "stub".into(),
        definition_version: "0".into(),
        definition: Value::Null,
        state: "s".into(),
        version: 0,
        input: json!({}),
        context: json!({}),
        started_at: Utc::now(),
        trace_id: None,
        run_id: None,
        cancelled_at: None,
        cancelled_reason: None,
        depth: 0,
        parent: None,
    }
}

fn run(args: Value) -> Result<Value, praxec_core::error::ExecutorError> {
    let req = ExecuteRequest {
        workflow: instance_stub(),
        transition: None,
        arguments: args,
        executor_config: Value::Null,
        idempotency_key: None,
        correlation_id: None,
    };
    futures::executor::block_on(DryRunExecutor.execute(req)).map(|r| r.output)
}

// ── Positive: dry-run returns a trace + start response ──────────────────────

#[test]
fn dry_run_returns_start_response_and_trace() {
    let definition = json!({
        "initialState": "s",
        "states": { "s": { "terminal": true } }
    });
    let out = run(json!({ "definition": definition })).expect("dry-run succeeds");
    assert_eq!(out["outcome"].as_str(), Some("ok"));
    assert!(
        out["start_response"].is_object(),
        "start_response object present"
    );
    let trace = out["trace"].as_array().expect("trace array");
    // At minimum the workflow.started event must appear.
    assert!(
        trace
            .iter()
            .any(|e| e["event_type"].as_str() == Some("workflow.started")),
        "trace must include workflow.started; got: {trace:?}"
    );
}

// ── Isolation: dry-run does not require any production state ───────────────

#[test]
fn dry_run_signature_takes_only_definition_and_input_no_store_param() {
    // This test is a compile-time witness — it constructs DryRunExecutor
    // with no caller state. If the public constructor ever gains a store
    // parameter, this test still compiles BUT the design intent is
    // violated; we check that the public surface remains parameterless.
    let _exec = DryRunExecutor;
}

#[test]
fn repeated_dry_runs_have_independent_traces() {
    let definition = json!({
        "initialState": "s",
        "states": { "s": { "terminal": true } }
    });
    let out_a = run(json!({ "definition": &definition })).expect("first dry-run");
    let out_b = run(json!({ "definition": &definition })).expect("second dry-run");

    // Each run uses a fresh in-memory store + audit sink. The workflow ids
    // generated by the runtime must therefore differ between calls.
    let a_id = out_a["start_response"]["workflow"]["id"]
        .as_str()
        .unwrap_or("");
    let b_id = out_b["start_response"]["workflow"]["id"]
        .as_str()
        .unwrap_or("");
    assert!(!a_id.is_empty() && !b_id.is_empty());
    assert_ne!(
        a_id, b_id,
        "fresh runtime per call must produce distinct workflow ids"
    );
}

// ── Negative: missing definition argument fails fast ───────────────────────

#[test]
fn missing_definition_errors() {
    let err = run(json!({})).expect_err("missing definition must error");
    assert!(format!("{err:?}").contains("definition"));
}

#[test]
fn malformed_definition_propagates_resolve_error() {
    // A definition without `initialState` will fail resolve.
    let err = run(json!({ "definition": { "states": {} } }))
        .expect_err("malformed definition must error");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("dry_run") || msg.contains("initialState"),
        "error should reference dry_run or the missing field; got: {msg}"
    );
}

// ── Edge: definition with no transitions completes at initial state ───────

#[test]
fn definition_with_no_transitions_completes_at_initial_state() {
    let definition = json!({
        "initialState": "only",
        "states": { "only": { "terminal": true } }
    });
    let out = run(json!({ "definition": definition })).expect("succeeds");
    let state = out["start_response"]["workflow"]["state"]
        .as_str()
        .unwrap_or("");
    assert_eq!(state, "only");
}
