//! T21 — Migrate v0.2 `--agent name=provider/model` CLI flags to a
//! v0.3 `models.yaml`. One-shot subcommand for operators with many
//! workflows that haven't moved off the legacy CLI path yet.
//!
//! Migration rules:
//! - Each `--agent NAME=PROVIDER/MODEL` becomes one binding under
//!   `overrides:` keyed by NAME (must parse as a valid `<affinity>` |
//!   `<tier>` | `<affinity>-<tier>` per the closed-enum schema). The
//!   single literal name `default` maps to the `default:` list.
//! - `models.yaml` REQUIRES a `default:` list (FMECA T2). If the CLI
//!   flags don't include one, the FIRST flag becomes the default too —
//!   the same binding then also appears under its named override slot.
//! - Names that don't parse as a valid delegate (e.g. legacy `planner`
//!   or `critic`) cause a hard error naming each offender. The
//!   operator can either rename their flags or hand-author the yaml.
//! - Duplicate names in the CLI are silently last-wins, mirroring
//!   `agent_config::build_registry`. Operators who pass the same name
//!   twice are doing so deliberately.

use std::collections::BTreeMap;
use std::path::Path;

use crate::agent_config::{AgentConfig, AgentConfigParseError};
use praxec_core::model_resolver::{ModelRef, ModelRefParseError};

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum MigrationError {
    #[error(transparent)]
    Parse(#[from] AgentConfigParseError),

    #[error(
        "no --agent flags provided. Pass one or more `--agent NAME=PROVIDER/MODEL` to migrate."
    )]
    NoAgents,

    #[error(
        "agent name(s) cannot be expressed in the models.yaml schema (closed enum: \
         <affinity> | <tier> | <affinity>-<tier> | `default`): {0:?}. Rename the flag(s) to a \
         valid delegate name, or author models.yaml by hand."
    )]
    UnmappableNames(Vec<String>),

    #[error("unknown provider `{provider}` in --agent {name}={provider}/{model}. Valid: anthropic | openai | gemini | openrouter | ollama | llamacpp | bedrock (use a `custom` endpoint in models.yaml for anything else; note: `google`→`gemini`, `lmstudio`→`custom`)")]
    UnknownProvider {
        name: String,
        provider: String,
        model: String,
    },
}

/// Translate a slice of CLI `--agent` specs into an `models.yaml` body.
/// Pure function: no I/O. The caller does the atomic write.
pub fn cli_args_to_yaml(specs: &[String]) -> Result<String, MigrationError> {
    if specs.is_empty() {
        return Err(MigrationError::NoAgents);
    }
    let configs: Vec<AgentConfig> = specs
        .iter()
        .map(|s| AgentConfig::parse_cli_arg(s))
        .collect::<Result<Vec<_>, _>>()?;

    // Last-wins dedupe by name. Build an ordered BTreeMap so the output
    // is deterministic — operators diff their generated file, so byte
    // stability across runs matters.
    let mut by_name: BTreeMap<String, &AgentConfig> = BTreeMap::new();
    for c in &configs {
        by_name.insert(c.name.clone(), c);
    }

    // Validate every name maps to a known schema slot. Collect ALL
    // unmappable names so the operator sees the full set at once
    // instead of fix-rebuild-error-fix-rebuild.
    let mut unmappable = Vec::new();
    for name in by_name.keys() {
        if name == "default" {
            continue;
        }
        match ModelRef::parse(name) {
            Ok(_) => {}
            Err(ModelRefParseError::Empty | ModelRefParseError::Unknown(_)) => {
                unmappable.push(name.clone());
            }
        }
    }
    if !unmappable.is_empty() {
        return Err(MigrationError::UnmappableNames(unmappable));
    }

    // Validate every provider name maps to a known closed-enum value.
    // Refuse silent custom/legacy fallbacks here; the operator's hand
    // is on the wheel for a one-shot migration.
    for cfg in by_name.values() {
        if !is_known_provider(&cfg.provider) {
            return Err(MigrationError::UnknownProvider {
                name: cfg.name.clone(),
                provider: cfg.provider.clone(),
                model: cfg.model.clone(),
            });
        }
    }

    // Pick the default binding. Operator's explicit `default` wins;
    // otherwise the first --agent in CLI order is promoted. Promoted
    // bindings stay in their original override slot too — duplicating
    // them is harmless and keeps the operator's intent visible.
    let default_cfg: &AgentConfig = if let Some(d) = by_name.get("default") {
        d
    } else {
        configs.first().expect("specs non-empty checked above")
    };

    // Build YAML by hand. ModelsFile only Deserializes today; a hand-
    // rolled emitter for the small surface is simpler than introducing
    // Serialize machinery that nothing else needs.
    let mut out = String::new();
    out.push_str("# Generated by `px migrate-agents-from-cli`.\n");
    out.push_str("# Review before committing — provider/model strings come straight from your\n");
    out.push_str("# --agent flags, but the schema layout is new.\n");
    out.push_str("version: 1\n");
    out.push_str("default:\n");
    push_binding(&mut out, default_cfg);
    let overrides: Vec<(&String, &&AgentConfig)> = by_name
        .iter()
        .filter(|(k, _)| k.as_str() != "default")
        .collect();
    if !overrides.is_empty() {
        out.push_str("overrides:\n");
        for (key, cfg) in overrides {
            out.push_str(&format!("  {key}:\n"));
            push_binding_indented(&mut out, cfg, "    ");
        }
    }
    Ok(out)
}

fn push_binding(out: &mut String, cfg: &AgentConfig) {
    push_binding_indented(out, cfg, "  ");
}

fn push_binding_indented(out: &mut String, cfg: &AgentConfig, indent: &str) {
    out.push_str(&format!("{indent}- provider:\n"));
    out.push_str(&format!("{indent}    name: {}\n", cfg.provider));
    out.push_str(&format!("{indent}  model: {}\n", cfg.model));
}

fn is_known_provider(slug: &str) -> bool {
    praxec_core::providers::ProviderId::from_slug(slug).is_some()
}

/// Atomic write: write to `<path>.tmp.<pid>` in the same directory,
/// fsync, then rename over `path`. The rename is atomic on POSIX
/// filesystems; partial writes are never visible to the file's
/// readers.
pub fn write_atomic(yaml: &str, path: &Path) -> std::io::Result<()> {
    let parent = path.parent().ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidInput, "path has no parent")
    })?;
    if !parent.as_os_str().is_empty() && !parent.exists() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension(format!("tmp.{}", std::process::id()));
    {
        use std::io::Write;
        let mut f = std::fs::File::create(&tmp)?;
        f.write_all(yaml.as_bytes())?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp, path)?;
    Ok(())
}
